---
name: CI

# https://github.com/actions/checkout
# https://github.com/ruby/setup-ruby
# https://github.com/actions/virtual-environments#available-environments
# https://github.com/ruby/setup-ruby/blob/master/README.md#supported-platforms
# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

'on': [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - head
        include:
          - os: windows-latest
            ruby: ruby
          - os: macos-latest
            ruby: ruby
          - os: ubuntu-latest
            ruby: ruby
            rubyopt: "--enable-frozen-string-literal"

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: install hoe
        run: gem install hoe -N

      - name: rake test
        run: |
          rake test
        timeout-minutes: 3

  isolated:
    name: >-
      test:isolated
    env:
      TESTOPTS: -v

    runs-on: ubuntu-latest
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler: none

      - name: install hoe
        run: gem install hoe -N

      - name: rake test:isolated
        run: |
          rake test:isolated RUBYOPT=--enable-frozen-string-literal
        timeout-minutes: 3
